import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InputGroup from "@/component/InputGroup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Could you accept my pr?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col min-h-screens justify-between items-center p-6 md:p-12">
          {children}
        </main>
      </body>
    </html>
  );
}
